#' @import methods RCurl S4Vectors

# Classes are placed roughly in order of dependence and sorted alphabetically
# where possible.

# Validation functions #########################################################

validateOperendSimpleList <- function (object) {
  if (missing(object)) {
    stop("Argument 'object' is required")
  }
  if (!inherits(object, "SimpleList")) {
    "Object is not a SimpleList"
  } else {
    # Check that slot 'elementType' matches value in class definition
    # Note: SimpleList validity check does not properly handle invalid
    #       'elementType' values (i.e., empty strings or vectors of length > 1)
    elementType <- getClass(class(object))@prototype@elementType
    if (!identical(object@elementType, elementType)) {
      paste("Slot 'elementType' must be set to", sQuote(elementType))
    } else {
      # If so, then perform basic SimpleList validity check
      validObject(as(object, "SimpleList"), test=TRUE)
    }
  }
}

# operendDate ##################################################################

#' @export operendDate
#' @rdname operendDate-class
#' @title Class to contain a time/date stamp
#' @description
#' This S4 class is a container for a time/date stamp in an Operend record.
#' @section Extends:
#' Directly extends class \code{\link{POSIXct}}.
#' @author Adam C. Gower \email{agower@@bu.edu}

operendDate <- setClass(
  "operendDate",
  prototype = NA_integer_,
  contains = "POSIXct"
)

#' @export operendPermissions
#' @rdname operendPermissions-class
#' @title Class to contain permissions for a record
#' @description
#' This S4 class is a container for a \code{\linkS4class{SimpleList}} of
#' character vectors containing permissions associated with an Operend record.
#' Each element of the list is named for the Group to which the permissions
#' apply, and may contain:
#' \describe{
#'   \item{\code{"C"}}{Create}
#'   \item{\code{"R"}}{Read}
#'   \item{\code{"U"}}{Update}
#'   \item{\code{"D"}}{Delete}
#'   \item{\code{"PR"}}{Permissions Read}
#'   \item{\code{"PU"}}{Permissions Update}
#' }
#' The list also contains a special element, named \code{`_other`},
#' that contains the permissions granted to Users in any remaining groups;
#' this element defaults to an empty vector (i.e., no permissions).
#' @author Adam C. Gower \email{agower@@bu.edu}

setClass(
  "operendPermissions",
  prototype = new("SimpleList", elementType="character"),
  validity = function (object)
  {
    # First perform standard validity check
    errors <- validateOperendSimpleList(object)
    if (isTRUE(errors)) errors <- c()
    # Then check that all elements of object have valid and unique names
    if (
      any(names(object) %in% c("", NA_character_)) ||
      any(duplicated(names(object)))
    ) {
      errors <- c(
        errors,
        paste(
          "All elements of an operendPermissions object",
          "must have valid and unique names"
        )
      )
    } else {
      # Then check to make sure all operations are valid
      operations <- c("C","R","U","D","PR","PU")
      for (name in names(object)) {
        if (any(!is.element(object[[name]], operations))) {
          errors <- c(
            errors,
            paste(
              "Values in", sQuote(name), "must be one of the following:",
              paste(sQuote(operations), collapse=",")
            )
          )
        }
      }
    }
    if (length(errors)) errors else TRUE
  },
  contains = "SimpleList"
)

#' @rdname operendPermissions-class
#' @param \dots
#' Arguments, named for each group, containing permissions for that group
#' @param _other
#' Argument containing permissions for all other groups

operendPermissions <- function (..., `_other`=character())
{
  new("operendPermissions", listData=list(..., `_other`=`_other`))
}

#' @export operendToken
#' @rdname operendToken-class
#' @title Class to contain an Operend token
#' @description
#' This class is an S4 representation of a token generated by an Operend Core
#' server.
#' @slot username
#' A character string specifying the name of the user associated with the token
#' @slot name
#' A character string specifying the name of the token
#' @slot authorizations
#' A character string specifying the authorizations associated with the token
#' @slot creationDate
#' A character string specifying the date the token was created
#' @slot secret
#' A character string encoding a JSON object that contains the information
#' needed to authenticate a call via the Operend API
#' @author Adam C. Gower \email{agower@@bu.edu}

operendToken <- setClass(
  "operendToken",
  slots = c(
    username       = "character",
    name           = "character",
    authorizations = "character",
    creationDate   = "character",
    secret         = "character"
  ),
  validity = function (object) {
    errors <- c()
    for (slotName in c("username", "name", "creationDate", "secret")) {
      if (length(slot(object, slotName)) != 1) {
        errors <- c(
          errors, paste("Slot", sQuote(slotName), "must be a character string")
        )
      }
    }
    if (length(object@authorizations) == 0) {
      errors <- c(errors, "Slot 'authorizations' must be of nonzero length")
    }
    if (!isTRUE(grepl("^[^:]+:[^:]+:[0-9A-Za-z]{40}$", object@secret))) {
      errors <- c(errors, "Token secret is incorrectly formatted")
    }
    if (length(errors)) errors else TRUE
  }
)

#' @export operendUser
#' @rdname operendUser-class
#' @title Class to contain data about a User
#' @description
#' This class is the S4 representation of the User record type.
#' It is a container for data about a given user.
#' @slot username
#' A character string specifying the name of the user.
#' Defaults to \code{""}.
#' @slot firstName
#' A character string specifying the first name of the user.
#' Defaults to \code{""}.
#' @slot lastName
#' A character string specifying the last name of the user.
#' Defaults to \code{""}.
#' @slot email
#' A character string specifying the email address of the user.
#' Defaults to \code{""}.
#' @slot active
#' A logical value specifying whether the user is active.
#' Defaults to \code{FALSE}.
#' @slot superuser
#' A logical value specifying whether the user is a superuser.
#' Defaults to \code{FALSE}.
#' @slot isReadOnlyUser
#' A logical value specifying whether the user has read-only access.
#' Defaults to \code{FALSE}.
#' @slot confirmed
#' A logical value specifying whether the user has been confirmed.
#' Defaults to \code{FALSE}.
#' @slot lastLogin
#' A character string specifying the timestamp of the User's last
#' authentication. Automatically updated by the system.
#' @slot dateJoined
#' A character string specifying the date that the User record was
#' created. Automatically populated when the record is created.
#' @slot group
#' A character string specifying the name of the default Group associated with
#' the user. Defaults to \code{""}.
#' @slot groups
#' A character array specifying the name(s) of the Group(s) associated with
#' the user. Defaults to an empty character vector.
#' @slot canAuthViaPassword
#' A logical value specifying whether the user can authenticate using
#' a username and password. Defaults to \code{FALSE}.
#' @slot canAuthViaGoogle
#' A logical value specifying whether the user can authenticate using
#' Google credentials. Defaults to \code{FALSE}.
#' @slot canAuthViaMicrosoft
#' A logical value specifying whether the user can authenticate using
#' Microsoft credentials. Defaults to \code{FALSE}.
#' @slot canAuthViaCILogon
#' A logical value specifying whether the user can authenticate using
#' CILogon credentials. Defaults to \code{FALSE}.
#' @slot hasMicrosoftOIDCSub
#' A logical value specifying whether the user has a Microsoft OIDC
#' (OpenID Connect) subscription. Defaults to \code{FALSE}.
#' @slot hasCILogonOIDCSub
#' A logical value specifying whether the user has a Microsoft OIDC
#' (OpenID Connect) subscription. Defaults to \code{FALSE}.
#' @seealso
#' \describe{
#'   \item{group}{
#'     This slot corresponds to the \code{\linkS4class{operendGroup}} object
#'     slot \code{name}.
#'   }
#' }
#' Functions for working with User records are described in \code{\link{Users}}.
#' @author Adam C. Gower \email{agower@@bu.edu}

operendUser <- setClass(
  "operendUser",
  slots = c(
    username            = "character",
    firstName           = "character",
    lastName            = "character",
    email               = "character",
    active              = "logical",
    superuser           = "logical",
    isReadOnlyUser      = "logical",
    confirmed           = "logical",
    lastLogin           = "operendDate",
    dateJoined          = "operendDate",
    group               = "character",
    groups              = "character",
    canAuthViaPassword  = "logical",
    canAuthViaGoogle    = "logical",
    canAuthViaMicrosoft = "logical",
    canAuthViaCILogon   = "logical",
    hasMicrosoftOIDCSub = "logical",
    hasCILogonOIDCSub   = "logical"
  ),
  prototype = prototype(
    username            = "",
    firstName           = "",
    lastName            = "",
    email               = "",
    active              = FALSE,
    superuser           = FALSE,
    isReadOnlyUser      = FALSE,
    confirmed           = FALSE,
    lastLogin           = new("operendDate"),
    dateJoined          = new("operendDate"),
    group               = "",
    groups              = character(),
    canAuthViaPassword  = FALSE,
    canAuthViaGoogle    = FALSE,
    canAuthViaMicrosoft = FALSE,
    canAuthViaCILogon   = FALSE,
    hasMicrosoftOIDCSub = FALSE,
    hasCILogonOIDCSub   = FALSE
  )
)

#' @export operendUserList
#' @rdname operendUserList-class
#' @title Class to contain a list of User objects
#' @description
#' This class is a container for one or more User objects.
#' @section Extends:
#' This class directly extends class \code{\linkS4class{SimpleList}}.
#' @author Adam C. Gower \email{agower@@bu.edu}

# Container for a list of operendUser objects
setClass(
  "operendUserList",
  prototype = new("SimpleList", elementType="operendUser"),
  validity = validateOperendSimpleList,
  contains = "SimpleList"
)

#' @rdname operendUserList-class
#' @param \dots
#' Objects of class \code{\linkS4class{operendUser}}

operendUserList <- function (...)
{
  new("operendUserList", listData=list(...))
}

#' @export operendGroup
#' @rdname operendGroup-class
#' @title Class to contain data about a Group
#' @description
#' This class is the S4 representation of the Group record type.
#' It is a container for data about a given group of Users.
#' @slot name
#' A character string specifying the name of the group.
#' Defaults to \code{""}.
#' @slot users
#' An \code{\linkS4class{operendUserList}} specifying the users in the group.
#' Defaults to an empty \code{operendUserList}.
#' @seealso
#' Functions for working with Group records are described in
#' \code{\link{Groups}}.
#' @author Adam C. Gower \email{agower@@bu.edu}

operendGroup <- setClass(
  "operendGroup",
  slots = c(
    name  = "character",
    users = "operendUserList"
  ),
  prototype = prototype(
    name  = "",
    users = operendUserList()
  )
)

#' @export operendGroupList
#' @rdname operendGroupList-class
#' @title Class to contain a list of Group objects
#' @description
#' This class is a container for one or more Group objects.
#' @section Extends:
#' This class directly extends class \code{\linkS4class{SimpleList}}.
#' @author Adam C. Gower \email{agower@@bu.edu}

# Container for a list of operendGroup objects
setClass(
  "operendGroupList",
  prototype = new("SimpleList", elementType="operendGroup"),
  validity = validateOperendSimpleList,
  contains = "SimpleList"
)

#' @rdname operendGroupList-class
#' @param \dots
#' Objects of or extending class \code{\linkS4class{operendGroup}}

operendGroupList <- function (...)
{
  new("operendGroupList", listData=list(...))
}

# WorkFile-related classes #####################################################

#' @export operendWorkFileIdList
#' @rdname operendWorkFileIdList-class
#' @title Class to contain a list of vectors of WorkFile IDs
#' @description
#' This class is a container for one or more integer vectors of \code{WorkFile}
#' identifers.
#' @section Extends:
#' This class directly extends class \code{\linkS4class{SimpleList}}.
#' @author Adam C. Gower \email{agower@@bu.edu}

# SimpleList of integer vectors
setClass(
  "operendWorkFileIdList",
  prototype = new("SimpleList", elementType="integer"),
  validity = validateOperendSimpleList,
  contains = "SimpleList"
)

#' @rdname operendWorkFileIdList-class
#' @param \dots
#' Integer vectors

operendWorkFileIdList <- function (...)
{
  new("operendWorkFileIdList", listData=list(...))
}

#' @export operendWorkFileProperties
#' @rdname operendWorkFileProperties-class
#' @title Class to contain WorkFile metadata
#' @description
#' This class is the S4 representation of the WorkFileProperties record
#' type.  It is a container for metadata about a given WorkFile.
#' @slot id
#' An integer value specifying the unique identifier of the WorkFile.
#' Automatically populated when the file is uploaded.
#' @slot hash
#' A character string specifying the MD5 checksum of the file.
#' Automatically populated when the file is uploaded.
#' @slot creator
#' A character string specifying the \code{username} of the User associated with
#' the record. Automatically populated when the file is uploaded.
#' @slot storage
#' A character string specifying the location in which the WorkFile is stored.
#' This is supplied by the user when the file is uploaded.
#' @slot creatorJobRun
#' An integer value specifying the identifier of the JobRun that created this
#' WorkFile.
#' @slot originalName
#' A character string specifying the original name of the file.
#' Automatically populated when the file is uploaded.
#' @slot originalModifiedTime
#' An \code{\linkS4class{operendDate}} object specifying the original timestamp
#' of the file.
#' @slot fileType
#' A character string specifying the type (e.g., extension) of the file.
#' Created when the file is uploaded.
#' @slot isTrashed
#' A logical value specifying whether the WorkFile is flagged to be
#' trashed. Defaults to \code{FALSE}.
#' @slot isTransient
#' A logical value specifying whether the WorkFile is flagged as
#' temporary. Defaults to \code{FALSE}.
#' @slot creationDatetime
#' An \code{\linkS4class{operendDate}} object specifying the date and time that
#' the record was created.
#' Automatically populated when the file is uploaded.
#' @slot length
#' A numeric value specifying the length of the file in bytes.
#' Automatically populated when the file is uploaded.
#' @slot token
#' A character string specifying a token that can be used for password-free
#' authentication. Automatically populated when the file is uploaded.
#' @slot permissions
#' An \code{\linkS4class{operendPermissions}} object specifying the permissions
#' associated with the record. Defaults to read-only.
#' @seealso
#' Functions for working with WorkFileProperties records are described in
#' \code{\link{WorkFileProperties}}.
#' @author Adam C. Gower \email{agower@@bu.edu}

operendWorkFileProperties <- setClass(
  "operendWorkFileProperties",
  slots = c(
    id                   = "integer",
    hash                 = "character",
    creator              = "character",
    storage              = "character",
    creatorJobRun        = "integer",
    originalName         = "character",
    originalModifiedTime = "operendDate",
    fileType             = "character",
    isTrashed            = "logical",
    isTransient          = "logical",
    creationDatetime     = "operendDate",
    length               = "numeric",
    token                = "character",
    permissions          = "operendPermissions"
  ),
  prototype = prototype(
    id                   = 0L,
    hash                 = "",
    creator              = "",
    storage              = "",
    creatorJobRun        = 0L,
    originalName         = "",
    originalModifiedTime = operendDate(
      as.POSIXct(-1, origin="1970-01-01", tz=getOption("opeRend")$timezone)
    ),
    fileType             = "",
    isTrashed            = FALSE,
    isTransient          = FALSE,
    creationDatetime     = new("operendDate"),
    length               = 0,
    token                = "",
    permissions          = new("operendPermissions")
  )
)

#' @export operendWorkFilePropertiesList
#' @rdname operendWorkFilePropertiesList-class
#' @title Class to contain a list of WorkFileProperties objects
#' @description
#' This class is a container for one or more WorkFileProperties objects.
#' @section Extends:
#' This class directly extends class \code{\linkS4class{SimpleList}}.
#' @author Adam C. Gower \email{agower@@bu.edu}

# Container for a list of operendWorkFileProperties objects
setClass(
  "operendWorkFilePropertiesList",
  prototype = new("SimpleList", elementType="operendWorkFileProperties"),
  validity = validateOperendSimpleList,
  contains = "SimpleList"
)

#' @rdname operendWorkFilePropertiesList-class
#' @param \dots
#' Objects of or extending class \code{\linkS4class{operendWorkFileProperties}}

operendWorkFilePropertiesList <- function (...)
{
  new("operendWorkFilePropertiesList", listData=list(...))
}

#' @export operendWorkFile
#' @rdname operendWorkFile-class
#' @title Class to provide a read-only connection to a WorkFile
#' @description
#' This class is a container for a \code{\link[base]{url}} object
#' that allows a token-based, read-only connection to a WorkFile.
#' @section Extends:
#' This class directly extends class \code{\link[base]{url}}.
#' @author Adam C. Gower \email{agower@@bu.edu}

setClass(
  "operendWorkFile",
  contains="url"
)

#' @rdname operendWorkFile-class
#' @param id
#' An integer-coercible value specifying the unique identifier of a
#' \code{WorkFile}.
#' @param open
#' A character string containing one of the following:
#' \describe{
#'   \item{""}{The connection is not opened.}
#'   \item{"r, rt"}{The connection is operend in read-only text mode.}
#'   \item{"rb"}{The connection is operend in read-only binary mode.}
#' }
#' An \code{operendWorkFile} may not be opened for writing or appending.
#' @return
#' An \code{operendWorkFile} object, containing
#' a read-only \code{\link[base]{url}} connection to the specified WorkFile,
#' opened for reading in text or binary mode if specified.

operendWorkFile <- function (id, open = c("", "r", "rt", "rb"))
{
  # Check arguments for errors
  if (missing(id)) {
    stop("Argument 'id' is required")
  } else {
    id <- suppressWarnings(as.integer(id))
    if (length(id) != 1 || is.na(id) || id <= 0) {
      stop("Argument 'id' must be coercible to a positive integer")
    }
  }

  if (!missing(open)) {
    if (!(is.character(open) && length(open) == 1)) {
      stop("Argument 'open' must be a character string")
    }
    # Note: match.arg does not work when called with "" against multiple choices
    if (open != "") open <- match.arg(open)
  } else {
    open <- match.arg(open)
  }

  # Check that a valid token is stored in the opeRend options
  if (!validObject(getOption("opeRend")$token)) {
    stop("A valid token must be stored in options('opeRend')")
  }

  # Create connection around URL to WorkFileContents API endpoint,
  # using token to authenticate via header
  con <- tryCatch(
    url(
      description = operendApiUrl("WorkFileContents", id),
      open = open,
      headers = c(
        "Accept" = "application/octet-stream",
        "Authorization" = paste("Bearer", getOption("opeRend")$token@secret)
      )
    ),
    error = function (condition) {
      stop(
        sprintf("Could not open connection to WorkFile '%s':\n", id),
        condition$message
      )
    }
  )
  new("operendWorkFile", con)
}

# JobRun-related classes #######################################################

#' @export operendJobRunParameters
#' @rdname operendJobRunParameters-class
#' @title Class to contain parameters for a JobRun
#' @description
#' This S4 class is a container for a \code{\linkS4class{SimpleList}} of
#' character vectors containing parameters associated with a JobRun.
#' Defaults to an empty \code{SimpleList}.
#' @author Adam C. Gower \email{agower@@bu.edu}

setClass(
  "operendJobRunParameters",
  prototype = new("SimpleList", elementType="character"),
  validity = validateOperendSimpleList,
  contains = "SimpleList"
)

#' @rdname operendJobRunParameters-class
#' @param \dots
#' Objects of class \code{character}

operendJobRunParameters <- function (...)
{
  new("operendJobRunParameters", listData=list(...))
}

#' @export operendJobRunStatusHistoryPoint
#' @rdname operendJobRunStatusHistoryPoint-class
#' @title Class to contain a JobRun status history point
#' @description
#' This class is a container for a status history point
#' associated with a JobRun.
#' @slot .Data
#' A character vector of length 2 specifying the status and its timestamp,
#' respectively.
#' @author Adam C. Gower \email{agower@@bu.edu}

operendJobRunStatusHistoryPoint <- setClass(
  "operendJobRunStatusHistoryPoint",
  contains = "character"
)

#' @export operendJobRunStatusHistory
#' @rdname operendJobRunStatusHistory-class
#' @title Class to contain a JobRun status history
#' @description
#' This class is a container for one or more
#' \code{\linkS4class{operendJobRunStatusHistoryPoint}} objects.
#' @section Extends:
#' This class directly extends class \code{\linkS4class{SimpleList}}.
#' @author Adam C. Gower \email{agower@@bu.edu}

# Container for a list of operendJobRunStatusHistoryPoint objects
setClass(
  "operendJobRunStatusHistory",
  prototype = new(
    "SimpleList", elementType="operendJobRunStatusHistoryPoint"
  ),
  validity = validateOperendSimpleList,
  contains = "SimpleList"
)

#' @rdname operendJobRunStatusHistory-class
#' @param \dots
#' Objects of class \code{\linkS4class{operendJobRunStatusHistoryPoint}}

operendJobRunStatusHistory <- function (...)
{
  new("operendJobRunStatusHistory", listData=list(...))
}

#' @export operendJobRunMessage
#' @rdname operendJobRunMessage-class
#' @title Class to contain a JobRun message
#' @description
#' This class is a container for a message associated with a JobRun.
#' @slot .Data
#' A character vector of length 2 specifying the message and its timestamp,
#' respectively.
#' @author Adam C. Gower \email{agower@@bu.edu}

operendJobRunMessage <- setClass(
  "operendJobRunMessage",
  contains = "character"
)

#' @export operendJobRunMessageLog
#' @rdname operendJobRunMessageLog-class
#' @title Class to contain a JobRun message log
#' @description
#' This class is a container for one or more
#' \code{\linkS4class{operendJobRunMessage}} objects.
#' @section Extends:
#' This class directly extends class \code{\linkS4class{SimpleList}}.
#' @author Adam C. Gower \email{agower@@bu.edu}

# Container for a list of operendJobRunMessage objects
setClass(
  "operendJobRunMessageLog",
  prototype = new("SimpleList", elementType="operendJobRunMessage"),
  validity = validateOperendSimpleList,
  contains = "SimpleList"
)

#' @rdname operendJobRunMessageLog-class
#' @param \dots
#' Objects of class \code{\linkS4class{operendJobRunMessage}}

operendJobRunMessageLog <- function (...)
{
  new("operendJobRunMessageLog", listData=list(...))
}

#' @export operendJobRunSubtask
#' @rdname operendJobRunSubtask-class
#' @title Class to contain a JobRun subtask
#' @description
#' This class is a container for a subtask of a JobRun.
#' @slot inputWorkFileIds
#' An \code{\linkS4class{operendWorkFileIdList}} object
#' @slot outputWorkFileIds
#' An \code{\linkS4class{operendWorkFileIdList}} object
#' @slot name
#' A character string specifying the name of the JobRun
#' @slot comments
#' A character string containing any comments about the JobRun
#' @author Adam C. Gower \email{agower@@bu.edu}

operendJobRunSubtask <- setClass(
  "operendJobRunSubtask",
  slots = c(
    inputWorkFileIds        = "operendWorkFileIdList",
    outputWorkFileIds       = "operendWorkFileIdList",
    name                    = "character",
    comments                = "character"
  ),
  prototype = prototype(
    inputWorkFileIds        = new("operendWorkFileIdList"),
    outputWorkFileIds       = new("operendWorkFileIdList"),
    name                    = "",
    comments                = ""
  )
)

#' @export operendJobRunSubtaskList
#' @rdname operendJobRunSubtaskList-class
#' @title Class to contain a list of JobRun subtasks
#' @description
#' This class is a container for one or more
#' \code{\linkS4class{operendJobRunSubtask}} objects.
#' @section Extends:
#' This class directly extends class \code{\linkS4class{SimpleList}}.
#' @author Adam C. Gower \email{agower@@bu.edu}

# Container for a list of operendJobRunSubtask objects
setClass(
  "operendJobRunSubtaskList",
  prototype = new("SimpleList", elementType="operendJobRunSubtask"),
  validity = validateOperendSimpleList,
  contains = "SimpleList"
)

#' @rdname operendJobRunSubtaskList-class
#' @param \dots
#' Objects of class \code{\linkS4class{operendJobRunSubtask}}

operendJobRunSubtaskList <- function (...)
{
  new("operendJobRunSubtaskList", listData=list(...))
}

#' @export operendJobRun
#' @rdname operendJobRun-class
#' @title Class to contain data about a JobRun
#' @description
#' This class is the S4 representation of the JobRun record type.
#' It is a container for data about a given job run.
#' @slot creator
#' A character string specifying the creator of the JobRun
#' @slot parameters
#' An \code{\linkS4class{operendJobRunParameters}} object
#' @slot inputWorkFileIds
#' An \code{\linkS4class{operendWorkFileIdList}} object
#' @slot outputWorkFileIds
#' An \code{\linkS4class{operendWorkFileIdList}} object
#' @slot allGeneratedWorkFileIds
#' An integer vector
#' @slot statusHistory
#' An \code{\linkS4class{operendJobRunStatusHistory}} object
#' @slot messageLog
#' A \code{operendJobRunMessageLog} object
#' @slot status
#' A character string specifying the status of the JobRun.
#' Defaults to \code{""}.
#' @slot id
#' An integer value
#' @slot jobTypeName
#' A character string specifying the type of the JobRun.
#' Defaults to \code{""}.
#' @slot subtasks
#' An \code{\linkS4class{operendJobRunSubtaskList}} object
#' @slot permissions
#' An \code{\linkS4class{operendPermissions}} object specifying the permissions
#' associated with the record. Defaults to read-only.
#' @author Adam C. Gower \email{agower@@bu.edu}

operendJobRun <- setClass(
  "operendJobRun",
  slots = c(
    id                      = "integer",
    creator                 = "character",
    parameters              = "operendJobRunParameters",
    inputWorkFileIds        = "operendWorkFileIdList",
    outputWorkFileIds       = "operendWorkFileIdList",
    allGeneratedWorkFileIds = "integer",
    statusHistory           = "operendJobRunStatusHistory",
    messageLog              = "operendJobRunMessageLog",
    status                  = "character",
    jobTypeName             = "character",
    subtasks                = "operendJobRunSubtaskList",
    permissions             = "operendPermissions"
  ),
  prototype = prototype(
    id                      = 0L,
    creator                 = "",
    parameters              = new("operendJobRunParameters"),
    inputWorkFileIds        = new("operendWorkFileIdList"),
    outputWorkFileIds       = new("operendWorkFileIdList"),
    allGeneratedWorkFileIds = integer(),
    statusHistory           = new("operendJobRunStatusHistory"),
    messageLog              = new("operendJobRunMessageLog"),
    status                  = "",
    jobTypeName             = "",
    subtasks                = new("operendJobRunSubtaskList"),
    permissions             = new("operendPermissions")
  )
)

#' @export operendJobRunList
#' @rdname operendJobRunList-class
#' @title Class to contain a list of JobRun objects
#' @description
#' This class is a container for one or more JobRun objects.
#' @section Extends:
#' This class directly extends class \code{\linkS4class{SimpleList}}.
#' @author Adam C. Gower \email{agower@@bu.edu}

# Container for a list of operendJobRun objects
setClass(
  "operendJobRunList",
  prototype = new("SimpleList", elementType="operendJobRun"),
  validity = validateOperendSimpleList,
  contains = "SimpleList"
)

#' @rdname operendJobRunList-class
#' @param \dots
#' Objects of class \code{\linkS4class{operendJobRun}}

operendJobRunList <- function (...)
{
  new("operendJobRunList", listData=list(...))
}

# EntityClass-related classes ##################################################

#' @export operendVariable
#' @rdname operendVariable-class
#' @title Class to contain Variable records
#' @description
#' This class is the S4 representation of the Variable
#' record type.  It is a container for a single variable associated with an
#' EntityClass record.
#' @slot category
#' A character string describing the category of the record.
#' Defaults to \code{NA}.
#' @slot type
#' A one-character string specifying the type of the record.
#' Defaults to \code{""}.  May take the value \code{'B'} (Boolean),
#' \code{'C'} (Code), \code{'D'} (Date), \code{'E'} (Entity),
#' \code{'F'} (Float), \code{'I'} (Integer), \code{'J'} (JobRun),
#' \code{'T'} (Text), or \code{'W'} (WorkFile).
#' @slot codes
#' A named character vector, where the names specify the allowed values that the
#' variable may take (if \code{type} is \code{'C'}), and the elements contain
#' the description of each code.
#' Defaults to an empty vector.
#' @slot entity_class_name
#' A character string specifying the name of the EntityClass that the
#' variable must belong to (if \code{type} is \code{'E'}).
#' Defaults to \code{NA}.
#' @slot is_array
#' A logical value specifying whether the variable is an array.
#' Defaults to \code{FALSE}.
#' @seealso
#' Variable objects are contained in
#' \code{\linkS4class{operendVariables}} objects.
#' @author Adam C. Gower \email{agower@@bu.edu}

operendVariable <- setClass(
  "operendVariable",
  slots = c(
    category          = "character",
    type              = "character",
    codes             = "character",
    entity_class_name = "character",
    is_array          = "logical"
  ),
  prototype = prototype(
    category          = NA_character_,
    type              = "",
    codes             = character(),
    entity_class_name = NA_character_,
    is_array          = FALSE
  ),
  validity = function (object)
  {
    errors <- c()
    # The 'type' slot must contain a single letter corresponding to a known type
    types <- c(
      boolean="B", code="C", date="D", entity="E", float="F", integer="I",
      jobRun="J", text="T", workFile="W"
    )
    if (length(object@type) != 1) {
      errors <- paste("The vector in slot 'type' must be of length 1")
    } else {
      if (!is.element(object@type, types)) {
        errors <- paste(
          "The value in slot 'type' must be one of the following:",
          paste(sQuote(types), collapse=",")
        )
      } else {
        # Check slot 'codes'
        if (((length(object@codes) > 0) != (object@type == "C"))) {
          errors <-
            "Slot 'codes' must contain values if and only if slot 'type' = 'C'"
        } else {
          # If type = 'C', names of the 'codes' slot must not contain NA values
          if (object@type == "C" && any(is.na(names(object@codes)))) {
            errors <- "Names of slot 'codes' may not contain any NA values"
          }
        }
        # Check slot 'entity_class_name'
        if (length(object@entity_class_name) != 1) {
          errors <- c(
            errors,
            paste("The vector in slot 'entity_class_name' must be of length 1")
          )
        } else {
          if (((!is.na(object@entity_class_name)) != (object@type == "E"))) {
            errors <- c(
              errors,
              paste(
                "Slot 'entity_class_name' must contain a non-NA value",
                "if and only if slot 'type' = 'E'"
              )
            )
          }
        }
      }
    }
    if (length(errors) == 0) TRUE else errors
  }
)

#' @export operendVariables
#' @rdname operendVariables-class
#' @title Class to contain Variables records
#' @description
#' This class is the S4 representation of the Variables
#' record type.
#' It is a container for the variables and metadata associated with a collection
#' of variable definitions in an EntityClass record.
#' @slot elementType
#' Contains the character string \code{"Variable"}.
#' @slot listData
#' A named list of \code{\linkS4class{operendVariable}} objects.
#' @section Extends:
#' Directly extends class \code{\linkS4class{SimpleList}}.
#' @seealso
#' Variables objects are contained in
#' \code{\linkS4class{operendEntityClass}} objects.
#' @author Adam C. Gower \email{agower@@bu.edu}

setClass(
  "operendVariables",
  prototype = new("SimpleList", elementType="operendVariable"),
  contains = "SimpleList"
)

#' @rdname operendVariables-class
#' @param \dots
#' Objects of class \code{\linkS4class{operendVariable}}

operendVariables <- function (...)
{
  new("operendVariables", listData=list(...))
}

#' @export operendEntityClass
#' @rdname operendEntityClass-class
#' @title Class to contain EntityClass records
#' @description
#' This class is the S4 representation of the EntityClass record type.
#' It is a container for the definition of an Entity class.
#' @slot name
#' A character string specifying the name of the record.
#' Defaults to \code{""}.
#' @slot description
#' A character string containing a description of the record.
#' Defaults to \code{""}.
#' @slot variables
#' An \code{\linkS4class{operendVariables}} object containing
#' any variables associated with the record.
#' @slot _updated
#' A character string specifying the time and date at which the record was last
#' updated. Defaults to \code{""}.
#' @slot _creation_date
#' A character string specifying the time and date at which the record was
#' created. Defaults to \code{""}.
#' @slot creator
#' A character string specifying the \code{username} of the User
#' who created the record. Defaults to \code{""}.
#' @slot owner
#' A character string specifying the \code{username} of the User
#' associated with the record. Defaults to \code{""}.
#' @slot permissions
#' An \code{\linkS4class{operendPermissions}} object specifying the permissions
#' associated with the record. Defaults to read-only.
#' @seealso
#' Functions for working with EntityClass records are
#' described in \code{\link{EntityClasses}}.
#' @author Adam C. Gower \email{agower@@bu.edu}

operendEntityClass <- setClass(
  "operendEntityClass",
  slots = c(
    name             = "character",
    description      = "character",
    variables        = "operendVariables",
    `_updated`       = "operendDate",
    `_creation_date` = "operendDate",
    creator          = "character",
    owner            = "character",
    permissions      = "operendPermissions"
  ),
  prototype = prototype(
    name             = "",
    description      = "",
    variables        = new("operendVariables"),
    `_updated`       = new("operendDate"),
    `_creation_date` = new("operendDate"),
    creator          = "",
    owner            = "",
    permissions      = new("operendPermissions")
  )
)

#' @export operendEntityClassList
#' @rdname operendEntityClassList-class
#' @title Class to contain a list of EntityClass objects
#' @description
#' This class is a container for one or more EntityClass objects.
#' @section Extends:
#' This class directly extends class \code{\linkS4class{SimpleList}}.
#' @author Adam C. Gower \email{agower@@bu.edu}

# Container for a list of operendEntityClass objects
setClass(
  "operendEntityClassList",
  prototype = new("SimpleList", elementType="operendEntityClass"),
  validity = validateOperendSimpleList,
  contains = "SimpleList"
)

#' @rdname operendEntityClassList-class
#' @param \dots
#' Objects of class \code{\linkS4class{operendEntityClass}}

operendEntityClassList <- function (...)
{
  new("operendEntityClassList", listData=list(...))
}

# Entity-related classes #######################################################

#' @export operendEntity
#' @rdname operendEntity-class
#' @title Class to contain Entity records
#' @description
#' This class is the S4 representation of the Entity record type.
#' It is a container for structured metadata and references to other Operend
#' records.
#' @slot _class
#' A character string specifying the Entity class of the record.
#' Defaults to \code{""}.
#' @slot _entity_id
#' A character string specifying the unique identifier of the record.
#' @slot _creation_date
#' A character string specifying the time and date at which the record was
#' created. Defaults to \code{""}.
#' @slot _jobruns
#' An integer vector containing the IDs of any JobRuns associated with the
#' record; used internally by the server-side app.
#' Defaults to an empty vector.
#' @slot _updated
#' A character string specifying the time and date at which the record was last
#' updated. Defaults to \code{""}.
#' @slot _workfiles
#' An integer vector containing the IDs of any WorkFiles associated with the
#' record; used internally by the server-side app.
#' Defaults to an empty vector.
#' @slot _creator
#' A character string specifying the \code{username} of the User that
#' created the record. Defaults to \code{""}.
#' @slot _owner
#' A character string specifying the \code{username} of the User that
#' owns the record. Defaults to \code{""}.
#' @slot _permissions
#' An \code{\linkS4class{operendPermissions}} object specifying the permissions
#' associated with the record. Defaults to read-only.
#' @slot .Data
#' A list of objects corresponding to the variables of the Entity.
#' @section Extends:
#' This class directly extends class \code{\linkS4class{SimpleList}}.
#' @author Adam C. Gower \email{agower@@bu.edu}

operendEntity <- setClass(
  "operendEntity",
  slots = c(
    `_class`         = "character",
    `_entity_id`     = "character",
    `_creation_date` = "operendDate",
    `_jobruns`       = "integer",
    `_updated`       = "operendDate",
    `_workfiles`     = "integer",
    `_creator`       = "character",
    `_owner`         = "character",
    `_permissions`   = "operendPermissions"
  ),
  prototype = prototype(
    `_class`         = "",
    `_entity_id`     = "",
    `_creation_date` = new("operendDate"),
    `_jobruns`       = integer(),
    `_updated`       = new("operendDate"),
    `_workfiles`     = integer(),
    `_creator`       = "",
    `_owner`         = "",
    `_permissions`   = new("operendPermissions")
  ),
  contains = "list"
)

#' @export operendEntityList
#' @rdname operendEntityList-class
#' @title Class to contain a list of Entity objects
#' @description
#' This class is a container for one or more Entity objects.
#' @section Extends:
#' This class directly extends class \code{\linkS4class{SimpleList}}.
#' @author Adam C. Gower \email{agower@@bu.edu}

# Container for a list of operendEntity objects
setClass(
  "operendEntityList",
  prototype = new("SimpleList", elementType="operendEntity"),
  validity = validateOperendSimpleList,
  contains = "SimpleList"
)

#' @rdname operendEntityList-class
#' @param \dots
#' Objects of or extending class \code{\linkS4class{operendEntity}}

operendEntityList <- function (...)
{
  new("operendEntityList", listData=list(...))
}
