# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

operendListToS4 <- function(x, object) {
    .Call('_opeRend_operendListToS4', PACKAGE = 'opeRend', x, object)
}

